services:
  # Inicjalizacja bazy danych
  mysql:
    container_name: mysql
    ports:
      - "3306:3306"
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: megatrans
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql/megatrans

  # Inicjalizacja Next JS
  megatrans-app:
    build:
      context: ./megatransfinal
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 3000:3000
      - 5555:5555
    restart: always

volumes:
  mysql:
